# Generated by Django 2.0.7 on 2018-07-11 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=200)),
                ('property_address', models.CharField(max_length=200)),
                ('property_zip', models.IntegerField(default=0)),
                ('property_state', models.CharField(max_length=200)),
                ('property_city', models.CharField(max_length=200)),
                ('property_price', models.IntegerField(default=0)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
