# Generated by Django 2.0.7 on 2018-07-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='last_price',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='property',
            name='outstanding_shares',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='property',
            name='rent_rate',
            field=models.IntegerField(default=0.0),
        ),
        migrations.AddField(
            model_name='property',
            name='total_shares',
            field=models.IntegerField(default=10000),
        ),
        migrations.AddField(
            model_name='property',
            name='volume',
            field=models.IntegerField(default=0),
        ),
    ]
