# Generated by Django 2.0.7 on 2018-07-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_auto_20180713_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='last_price',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
