# Generated by Django 2.0.7 on 2018-07-13 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_auto_20180713_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='property',
            name='rent_rate',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='property',
            name='total_shares',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
